tasks:
  - name: server
    before: |
      cd server
    init: |
      npm install
    command: |
      npm run dev
  - name: client
    before: |
      cd client
    init: |
      npm install
    command: |
      npm start

ports:
  - port: 3000
    onOpen: open-browser
  
vscode:
  extensions:
    - vscode-icons-team.vscode-icons
    - zhuangtongfa.material-theme
