version: '3'
services:
  calzlet:
    build: .
    # ports:
    #   - "5000:5000"
    # managed by the proxy
    volumes:
      - "./images:/app/images:rw"
    environment:
      - MONGODB_URI
      - JWT_SECRET
      - HCAPTCHA_SECRET
      - SMTP_EMAIL
      - SMTP_PASSWORD
      - BASE_URL