version: '3'
services:
  calzlet:
    image: ghcr.io/caalek/calzlet:latest
    # ports:
    #   - "5000:5000"
    # managed by the proxy
    volumes:
      - "./images:/app/images:rw"
    environment:
      - MONGODB_URI
      - JWT_SECRET
      - HCAPTCHA_SECRET
      - SMTP_EMAIL
      - SMTP_PASSWORD
      - BASE_URL
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST
    restart: unless-stopped
    networks:
     - net

networks:
  net:
    external: true