name: remote ssh command
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Keys and known_hosts
        uses: actions/checkout@v1
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.GH_PRIVATE_KEY }}"
      
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: cd calzlet && git pull origin master && docker compose up -d --build